version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: phd-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-changeme123}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery-worker:
    build:
      context: ../..
      dockerfile: Dockerfile.celery
    container_name: phd-celery-worker
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD:-changeme123}@redis:6379/0
    volumes:
      - ../../:/app
    working_dir: /app
    command: celery -A tasks worker --loglevel=info --concurrency=4
    restart: unless-stopped

  celery-beat:
    build:
      context: ../..
      dockerfile: Dockerfile.celery
    container_name: phd-celery-beat
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD:-changeme123}@redis:6379/0
    volumes:
      - ../../:/app
    working_dir: /app
    command: celery -A tasks beat --loglevel=info
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: phd-network